### ISSUE TITLE
Swap Lineage and input sections

### ISSUE THREAD

**Issue by frossano-grafana** [grafana/play-thema#36]
To be confirmed with Joseph.
We should swap the input and lineage sections because it flows logically to validate a specific input against a lineage

**Comment by joanlopez** [comment]
As discussed with @sdboyer, this looks like it should be closed. Right @frossano-grafana?

**Comment by frossano-grafana** [comment]
I removed it from the Thema playground Epic, we can close it now and reopen it if we realise people are confused, or that we get feedback about this
