### ISSUE TITLE
Update thema to incorporate lineage flattening

### ISSUE THREAD

**Issue by sdboyer** [grafana/play-thema#58]
The playground isn't using the new flattened lineage form. Would be great to see it updated, particularly so that it's useful for writing new docs for thema itself.

**Comment by joanlopez** [comment]
Mmm... could this be an old version cached? 🤔 
[This pull request](https://github.com/grafana/play-thema/pull/38) which updates Thema version and incorporates lineage flattening was merged one month ago. And, indeed, if I try to use the Thema Playground now, and I load one of the available examples, it's in its flattened formed.

**Comment by sdboyer** [comment]
whoops! it's because i keep going to an old share link - https://grafana.github.io/play-thema/#88Wa3y_HSl4
